server:
  port: 8080

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
    default-schema: public
    liquibase-schema: public

application:
  jwt:
    secretKey: Ja0Zj+3ISWHl2k+JNVv1XwckwS4CHqfYwXvvAj97Uq4=