version: '1.0'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    restart: on-failure:3
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  vault:
    container_name: vault
    image: hashicorp/vault
    ports:
      - 8200:8200
    volumes:
      - ./vault/file/:/vault/file:rw
      - ./vault/config/:/vault/config:rw
      - ./vault/logs/:/vault/logs:rw
    command:
      - server
    restart: on-failure:3