DB_SCHEMA: kpo

server:
  port: 8080

spring:
  application:
    name: kollok
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db}
    driver-class-name: org.postgresql.Driver
    username: ${postgres.user}
    password: ${postgres.password}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${DB_SCHEMA}
    locations: classpath:db.migrations